version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
